const spectrumCards = [
  ["Hot", "Cold"],
  ["Overrated", "Underrated"],
  ["Good", "Evil"],
  ["Fantasy", "Reality"],
  ["Rough", "Smooth"],
  ["Sad Song", "Happy Song"],
  ["Useless Superpower", "Useful Superpower"],
  ["Harmless", "Harmful"],
  ["Boring", "Exciting"],
  ["Ugly", "Beautiful"],
  ["Terrible Movie", "Great Movie"],
  ["Easy to Spell", "Hard to Spell"],
  ["Guilty Pleasure", "Healthy Hobby"],
  ["Round", "Pointy"],
  ["Smells Bad", "Smells Good"],
  ["Mainstream", "Niche"],
  ["Old School", "Modern"],
  ["Cheap", "Expensive"],
  ["Quiet", "Loud"],
  ["Small", "Big"],
  ["Slow", "Fast"],
  ["Weak", "Strong"],
  ["Simple", "Complex"],
  ["Common", "Rare"],
  ["Light", "Heavy"],
  ["Sweet", "Sour"],
  ["Safe", "Dangerous"],
  ["Normal", "Weird"],
  ["Easy", "Difficult"],
  ["Funny", "Serious"],
  ["Tastes Bad", "Tastes Good"],
  ["Villain", "Hero"],
  ["Short-lived", "Long-lasting"],
  ["Forgettable", "Unforgettable"],
  ["Relaxing", "Stressful"],
  ["Soft", "Hard"],
  ["Wet", "Dry"],
  ["Man-made", "Natural"],
  ["Empty", "Full"],
  ["Young", "Old"],
  ["Bad First Date", "Good First Date"],
  ["Needs Salt", "Too Salty"],
  ["Underpaid", "Overpaid"],
  ["Movie", "Book"],
  ["Brain", "Brawn"],
  ["Introvert", "Extrovert"],
  ["Cat Person", "Dog Person"],
  ["Morning Person", "Night Owl"],
  ["Indoor Activity", "Outdoor Activity"],
  ["Sandwich", "Not a Sandwich"],
  ["Skill", "Luck"],
  ["Art", "Science"],
  ["Tourist Trap", "Hidden Gem"],
  ["Trend", "Classic"],
  ["Cringe", "Cool"],
  ["Snack", "Meal"],
  ["Bad Habit", "Good Habit"],
  ["Scary", "Not Scary"],
  ["Romantic", "Unromantic"],
  ["Childhood", "Adulthood"],
];

export default spectrumCards;
